name: Lint and Run Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytelegrambotapi flake8

      - name: Run linter
        run: |
          flake8 . --count --max-line-length=100 --statistics

      - name: Run bot
        if: success() # запускаем только если линтер прошёл
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python main.py
