name: CI/CD for Telegram Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytelegrambotapi flake8

      - name: Run linter
        run: |
          flake8 . --count --max-line-length=100 --statistics

      - name: Deploy to server (via SSH)
        if: success()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/bot
            git pull origin main
            systemctl restart mybot.service